services:

  pokestral-showdown:
    build: scraping
    container_name: pokestral-scraping
    ports:
      - "3110:8000"
    networks:
      - pokestral-network
    restart: unless-stopped

networks:
  pokestral-network:
    driver: bridge